[package]
name = "glacialcast-dash"
edition.workspace = true
description = "CENC-encrypted fragmented MP4 and MPEG-DASH generation for GlacialCast."
license.workspace = true
repository.workspace = true
publish = false
version.workspace = true

[dependencies]
aes.workspace = true
aes-gcm.workspace = true
base64.workspace = true
ctr.workspace = true
hkdf.workspace = true
hmac.workspace = true
rand.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
