//! Constrained MPEG-DASH, fragmented MP4, and cursor-crypto primitives.
//!
//! GlacialCast uses this crate to turn H.264 Annex-B access units into
//! Common-Encryption (`cenc`) protected fragmented MP4, derive per-epoch keys
//! from an out-of-band viewer key, encode the independently timed cursor
//! overlay, and build the matching MPD. It intentionally implements only the
//! media profile generated by GlacialCast rather than a general-purpose DASH
//! stack.
//!
//! All public parsers validate their size and structural invariants before
//! returning data. Media encryption uses AES-128-CTR as required by CENC;
//! cursor batches use AES-256-GCM; and object authentication uses HMAC-SHA-256.

#![deny(missing_docs)]

use aes::Aes128;
use aes_gcm::{
    Aes256Gcm, KeyInit, Nonce,
    aead::{Aead, Payload},
};
use base64::{Engine, engine::general_purpose::URL_SAFE_NO_PAD};
use ctr::cipher::{KeyIvInit, StreamCipher};
use hkdf::Hkdf;
use hmac::{Hmac, Mac};
use rand::{RngCore, rngs::OsRng};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};
use std::fmt::Write as _;
use thiserror::Error;
use uuid::Uuid;

type Aes128Ctr = ctr::Ctr128BE<Aes128>;
type HmacSha256 = Hmac<Sha256>;

/// Version of the serialized epoch descriptor and DASH object profile.
pub const DASH_FORMAT_VERSION: u16 = 1;
/// Media and cursor timestamp ticks per second.
pub const MEDIA_TIMESCALE: u32 = 90_000;
/// Duration of a one-frame-per-second sample in [`MEDIA_TIMESCALE`] ticks.
pub const DEFAULT_FRAME_DURATION: u32 = MEDIA_TIMESCALE;
/// Default number of video frames in a random-access segment.
pub const DEFAULT_SEGMENT_FRAMES: u16 = 4;
/// Maximum accepted H.264 access-unit or encrypted media payload size.
pub const MAX_MEDIA_PAYLOAD: usize = 32 * 1024 * 1024;
/// Maximum encoded encrypted cursor-batch size.
pub const MAX_CURSOR_PAYLOAD: usize = 4 * 1024 * 1024;
/// Maximum width or height of an RGBA cursor bitmap.
pub const MAX_CURSOR_BITMAP_SIDE: u32 = 512;
const ENCRYPTED_CURSOR_HEADER_LEN: usize = 16;
const AES_GCM_TAG_LEN: usize = 16;
const MAX_CURSOR_PLAINTEXT: usize =
    MAX_CURSOR_PAYLOAD - ENCRYPTED_CURSOR_HEADER_LEN - AES_GCM_TAG_LEN;
const CURSOR_BATCH_HEADER_LEN: usize = 14;
const CURSOR_EVENT_LEN: usize = 33;
const CURSOR_BITMAP_HEADER_LEN: usize = 20;

#[derive(Debug, Error)]
/// Errors produced while validating, encrypting, or packaging DASH data.
pub enum DashError {
    /// An H.264 access unit contained no nonempty Annex-B NAL unit.
    #[error("H264 access unit does not contain an Annex-B NAL unit")]
    EmptyAccessUnit,
    /// The supplied H.264 sequence parameter set was too short.
    #[error("H264 SPS must contain at least four bytes")]
    InvalidSps,
    /// The supplied H.264 picture parameter set was empty.
    #[error("H264 PPS must not be empty")]
    InvalidPps,
    /// A media input or result exceeded [`MAX_MEDIA_PAYLOAD`].
    #[error("media payload exceeds {MAX_MEDIA_PAYLOAD} bytes")]
    MediaTooLarge,
    /// A cursor batch exceeded [`MAX_CURSOR_PAYLOAD`].
    #[error("cursor payload exceeds {MAX_CURSOR_PAYLOAD} bytes")]
    CursorTooLarge,
    /// A cursor batch or encrypted cursor envelope violated its wire format.
    #[error("cursor payload is malformed")]
    InvalidCursorPayload,
    /// CENC auxiliary sample information did not fit the selected MP4 layout.
    #[error("CENC auxiliary data exceeds one-byte saiz representation")]
    AuxiliaryInfoTooLarge,
    /// Encryption, decryption, or authentication failed.
    #[error("cryptographic operation failed")]
    Crypto,
    /// JSON serialization or deserialization failed.
    #[error("serialization failed: {0}")]
    Serialization(#[from] serde_json::Error),
    /// HKDF could not produce the fixed-size epoch key material.
    #[error("HKDF output length is invalid")]
    Hkdf,
    /// A URL-safe base64 value could not be decoded.
    #[error("base64 decode failed: {0}")]
    Base64(#[from] base64::DecodeError),
    /// A decoded viewer key had the reported length instead of 32 bytes.
    #[error("viewer key must decode to 32 bytes, got {0}")]
    InvalidViewerKey(usize),
    /// An epoch descriptor violated the supported media profile.
    #[error("invalid DASH epoch descriptor")]
    InvalidEpochDescriptor,
}

/// Result type returned by DASH and cursor operations.
pub type Result<T> = std::result::Result<T, DashError>;

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
/// Authenticated metadata that defines one capture and encryption epoch.
pub struct EpochDescriptor {
    /// [`DASH_FORMAT_VERSION`] used to encode the descriptor.
    pub format_version: u16,
    /// Durable stream identity assigned by the relay.
    pub stream_id: Uuid,
    /// Capture epoch identity; also determines [`Self::key_id`].
    pub epoch_id: Uuid,
    /// CENC key identifier, equal to the raw epoch UUID bytes.
    pub key_id: [u8; 16],
    /// Encoded video width in pixels.
    pub width: u16,
    /// Encoded video height in pixels.
    pub height: u16,
    /// RFC 6381 AVC codec string, such as `avc1.42c01f`.
    pub codec: String,
    /// Timestamp ticks per second; currently [`MEDIA_TIMESCALE`].
    pub timescale: u32,
    /// Number of video frames in each random-access segment.
    pub segment_frames: u16,
    /// RFC 3339 availability start time used by the live MPD.
    pub availability_start_time: String,
    /// Whether this epoch's media and cursor payloads are encrypted.
    ///
    /// Defaults to `true` when absent, so a descriptor written before this
    /// field existed still reads as the encrypted epoch it is, and retained
    /// objects survive the upgrade.
    ///
    /// A `false` epoch has no viewer key, and therefore no key to derive an
    /// authentication tag from either: its objects are unauthenticated, and
    /// integrity rests on Noise for ingest and TLS to the browser rather than
    /// end to end. Publishing one is refused unless the relay is serving a
    /// trusted LAN.
    #[serde(default = "encrypted_by_default")]
    pub encrypted: bool,
}

/// Absent means encrypted: the only descriptors without the field predate it.
fn encrypted_by_default() -> bool {
    true
}

impl EpochDescriptor {
    /// Validates the descriptor against the supported GlacialCast profile.
    pub fn validate(&self) -> Result<()> {
        if self.format_version != DASH_FORMAT_VERSION
            || self.stream_id.is_nil()
            || self.epoch_id.is_nil()
            || self.key_id != *self.epoch_id.as_bytes()
            || self.width == 0
            || self.height == 0
            || self.timescale != MEDIA_TIMESCALE
            || self.segment_frames == 0
            || !self.codec.starts_with("avc1.")
            || self.codec.len() > 32
            || self.availability_start_time.len() > 64
            // An unencrypted epoch has no key, so it has no key identifier to
            // carry; requiring the epoch UUID there anyway keeps one shape for
            // both modes and one thing for a reader to check.
            || (!self.encrypted && self.key_id != *self.epoch_id.as_bytes())
        {
            return Err(DashError::InvalidEpochDescriptor);
        }
        Ok(())
    }

    /// Validates and serializes the descriptor as UTF-8 JSON.
    pub fn to_json(&self) -> Result<Vec<u8>> {
        self.validate()?;
        Ok(serde_json::to_vec(self)?)
    }

    /// Parses JSON and validates the resulting descriptor.
    pub fn from_json(bytes: &[u8]) -> Result<Self> {
        let descriptor: Self = serde_json::from_slice(bytes)?;
        descriptor.validate()?;
        Ok(descriptor)
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
/// Keys derived for one stream epoch from the out-of-band viewer key.
pub struct EpochKeys {
    /// CENC key identifier embedded in the initialization segment and MPD.
    pub key_id: [u8; 16],
    /// AES-128-CTR key used for CENC video samples.
    pub cenc_key: [u8; 16],
    /// AES-256-GCM key used for cursor batches.
    pub cursor_key: [u8; 32],
    /// HMAC-SHA-256 key used to authenticate complete stream objects.
    pub authentication_key: [u8; 32],
}

impl EpochKeys {
    /// Derives domain-separated epoch keys for `stream_id` and `epoch_id`.
    ///
    /// Reusing a viewer key across epochs is safe because both identifiers are
    /// incorporated into the HKDF salt.
    ///
    /// # Examples
    ///
    /// ```
    /// use glacialcast_dash::EpochKeys;
    /// use uuid::Uuid;
    ///
    /// let stream_id = Uuid::from_u128(1);
    /// let epoch_id = Uuid::from_u128(2);
    /// let keys = EpochKeys::derive(&[7; 32], stream_id, epoch_id)?;
    ///
    /// assert_eq!(keys.key_id, *epoch_id.as_bytes());
    /// # Ok::<(), glacialcast_dash::DashError>(())
    /// ```
    pub fn derive(viewer_key: &[u8; 32], stream_id: Uuid, epoch_id: Uuid) -> Result<Self> {
        let mut salt_hasher = Sha256::new();
        salt_hasher.update(b"glacialcast epoch key salt");
        salt_hasher.update(stream_id.as_bytes());
        salt_hasher.update(epoch_id.as_bytes());
        let salt = salt_hasher.finalize();
        let hkdf = Hkdf::<Sha256>::new(Some(&salt), viewer_key);
        let mut material = [0u8; 80];
        hkdf.expand(b"glacialcast dash epoch keys v1", &mut material)
            .map_err(|_| DashError::Hkdf)?;

        let mut cenc_key = [0u8; 16];
        cenc_key.copy_from_slice(&material[..16]);
        let mut cursor_key = [0u8; 32];
        cursor_key.copy_from_slice(&material[16..48]);
        let mut authentication_key = [0u8; 32];
        authentication_key.copy_from_slice(&material[48..80]);

        Ok(Self {
            key_id: *epoch_id.as_bytes(),
            cenc_key,
            cursor_key,
            authentication_key,
        })
    }

    /// Encodes the CENC key identifier as unpadded URL-safe base64.
    pub fn key_id_b64(&self) -> String {
        URL_SAFE_NO_PAD.encode(self.key_id)
    }

    /// Encodes the CENC content key as unpadded URL-safe base64.
    ///
    /// This value is intended for the in-browser Clear Key session and must
    /// not be sent to the relay or written to logs.
    pub fn cenc_key_b64(&self) -> String {
        URL_SAFE_NO_PAD.encode(self.cenc_key)
    }
}

/// Generates a cryptographically random 32-byte viewer key in URL-safe base64.
pub fn random_viewer_key_b64() -> String {
    let mut key = [0u8; 32];
    OsRng.fill_bytes(&mut key);
    URL_SAFE_NO_PAD.encode(key)
}

/// Decodes an unpadded URL-safe base64 viewer key and enforces 32 bytes.
pub fn decode_viewer_key_b64(encoded: &str) -> Result<[u8; 32]> {
    let decoded = URL_SAFE_NO_PAD.decode(encoded.trim())?;
    if decoded.len() != 32 {
        return Err(DashError::InvalidViewerKey(decoded.len()));
    }
    let mut key = [0u8; 32];
    key.copy_from_slice(&decoded);
    Ok(key)
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
/// One cursor state change on the shared media timeline.
pub struct CursorEvent {
    /// Event time in [`MEDIA_TIMESCALE`] ticks.
    pub timestamp: u64,
    /// Horizontal source coordinate in millionths of a pixel.
    pub x_micropixels: i64,
    /// Vertical source coordinate in millionths of a pixel.
    pub y_micropixels: i64,
    /// Whether the cursor should be rendered after this event.
    pub visible: bool,
    /// Stable identity of the active bitmap, or zero while hidden.
    pub bitmap_id: u64,
    /// New RGBA bitmap data when the bitmap changed or was refreshed.
    pub bitmap: Option<CursorBitmap>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
/// An unpremultiplied, row-major RGBA cursor image and hotspot.
pub struct CursorBitmap {
    /// Bitmap width in pixels.
    pub width: u32,
    /// Bitmap height in pixels.
    pub height: u32,
    /// Horizontal hotspot offset in pixels.
    pub hotspot_x: i32,
    /// Vertical hotspot offset in pixels.
    pub hotspot_y: i32,
    /// Exactly `width * height * 4` row-major RGBA bytes.
    pub rgba: Vec<u8>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
/// Ordered cursor events captured for one source and time range.
pub struct CursorBatch {
    /// Captured source width used to validate and scale coordinates.
    pub source_width: u32,
    /// Captured source height used to validate and scale coordinates.
    pub source_height: u32,
    /// Nonempty events ordered by ascending timestamp.
    pub events: Vec<CursorEvent>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
/// AES-256-GCM envelope containing one encoded [`CursorBatch`].
pub struct EncryptedCursorBatch {
    /// Unique random GCM nonce.
    pub nonce: [u8; 12],
    /// Ciphertext followed by the GCM authentication tag.
    pub ciphertext: Vec<u8>,
}

impl EncryptedCursorBatch {
    /// Encodes the bounded `GCE1` portable cursor envelope.
    pub fn to_bytes(&self) -> Result<Vec<u8>> {
        validate_encrypted_cursor_batch(self)?;
        let mut bytes = Vec::with_capacity(ENCRYPTED_CURSOR_HEADER_LEN + self.ciphertext.len());
        bytes.extend_from_slice(b"GCE1");
        bytes.extend_from_slice(&self.nonce);
        bytes.extend_from_slice(&self.ciphertext);
        Ok(bytes)
    }

    /// Parses the `GCE1` envelope without decrypting its contents.
    pub fn from_bytes(bytes: &[u8]) -> Result<Self> {
        if bytes.len() < ENCRYPTED_CURSOR_HEADER_LEN + AES_GCM_TAG_LEN
            || bytes.len() > MAX_CURSOR_PAYLOAD
            || &bytes[..4] != b"GCE1"
        {
            return Err(DashError::InvalidCursorPayload);
        }
        let mut nonce = [0u8; 12];
        nonce.copy_from_slice(&bytes[4..16]);
        Ok(Self {
            nonce,
            ciphertext: bytes[16..].to_vec(),
        })
    }
}

#[derive(Debug, Clone, Copy)]
/// Public routing metadata authenticated as cursor associated data.
pub struct CursorContext {
    /// Stream to which the cursor object belongs.
    pub stream_id: Uuid,
    /// Capture epoch to which the cursor object belongs.
    pub epoch_id: Uuid,
    /// Monotonic stream-object sequence number.
    pub sequence: u64,
    /// First permitted event time in [`MEDIA_TIMESCALE`] ticks.
    pub start_timestamp: u64,
    /// Captured source width expected in the decrypted batch.
    pub source_width: u32,
    /// Captured source height expected in the decrypted batch.
    pub source_height: u32,
}

/// Validates, encodes, and encrypts a cursor batch with authenticated context.
pub fn encrypt_cursor_batch(
    keys: &EpochKeys,
    context: CursorContext,
    batch: &CursorBatch,
) -> Result<EncryptedCursorBatch> {
    validate_cursor_batch(batch)?;
    validate_cursor_context(batch, context)?;
    let plaintext = encode_cursor_batch(batch)?;
    let mut nonce = [0u8; 12];
    OsRng.fill_bytes(&mut nonce);
    let cipher = Aes256Gcm::new((&keys.cursor_key).into());
    let ciphertext = cipher
        .encrypt(
            Nonce::from_slice(&nonce),
            Payload {
                msg: &plaintext,
                aad: &cursor_aad(context),
            },
        )
        .map_err(|_| DashError::Crypto)?;
    Ok(EncryptedCursorBatch { nonce, ciphertext })
}

/// Authenticates, decrypts, decodes, and validates a cursor batch.
pub fn decrypt_cursor_batch(
    keys: &EpochKeys,
    context: CursorContext,
    encrypted: &EncryptedCursorBatch,
) -> Result<CursorBatch> {
    validate_encrypted_cursor_batch(encrypted)?;
    let cipher = Aes256Gcm::new((&keys.cursor_key).into());
    let plaintext = cipher
        .decrypt(
            Nonce::from_slice(&encrypted.nonce),
            Payload {
                msg: &encrypted.ciphertext,
                aad: &cursor_aad(context),
            },
        )
        .map_err(|_| DashError::Crypto)?;
    let batch = decode_cursor_batch(&plaintext)?;
    validate_cursor_batch(&batch)?;
    validate_cursor_context(&batch, context)?;
    Ok(batch)
}

fn encode_cursor_batch(batch: &CursorBatch) -> Result<Vec<u8>> {
    let encoded_len = cursor_batch_encoded_len(batch)?;
    let event_count = u16::try_from(batch.events.len()).map_err(|_| DashError::CursorTooLarge)?;
    let mut bytes = Vec::with_capacity(encoded_len);
    bytes.extend_from_slice(b"GCC1");
    bytes.extend_from_slice(&batch.source_width.to_be_bytes());
    bytes.extend_from_slice(&batch.source_height.to_be_bytes());
    bytes.extend_from_slice(&event_count.to_be_bytes());
    for event in &batch.events {
        bytes.extend_from_slice(&event.timestamp.to_be_bytes());
        bytes.extend_from_slice(&event.x_micropixels.to_be_bytes());
        bytes.extend_from_slice(&event.y_micropixels.to_be_bytes());
        let mut flags = u8::from(event.visible);
        if event.bitmap.is_some() {
            flags |= 1 << 1;
        }
        bytes.push(flags);
        bytes.extend_from_slice(&event.bitmap_id.to_be_bytes());
        if let Some(bitmap) = &event.bitmap {
            bytes.extend_from_slice(&bitmap.width.to_be_bytes());
            bytes.extend_from_slice(&bitmap.height.to_be_bytes());
            bytes.extend_from_slice(&bitmap.hotspot_x.to_be_bytes());
            bytes.extend_from_slice(&bitmap.hotspot_y.to_be_bytes());
            let rgba_len =
                u32::try_from(bitmap.rgba.len()).map_err(|_| DashError::CursorTooLarge)?;
            bytes.extend_from_slice(&rgba_len.to_be_bytes());
            bytes.extend_from_slice(&bitmap.rgba);
        }
    }
    debug_assert_eq!(bytes.len(), encoded_len);
    Ok(bytes)
}

fn decode_cursor_batch(bytes: &[u8]) -> Result<CursorBatch> {
    if bytes.len() > MAX_CURSOR_PLAINTEXT {
        return Err(DashError::CursorTooLarge);
    }
    let mut reader = CursorReader::new(bytes);
    if reader.take(4)? != b"GCC1" {
        return Err(DashError::InvalidCursorPayload);
    }
    let source_width = reader.u32()?;
    let source_height = reader.u32()?;
    let event_count = reader.u16()?;
    let minimum_event_bytes = usize::from(event_count)
        .checked_mul(CURSOR_EVENT_LEN)
        .ok_or(DashError::InvalidCursorPayload)?;
    if reader.remaining() < minimum_event_bytes {
        return Err(DashError::InvalidCursorPayload);
    }
    let mut events = Vec::with_capacity(usize::from(event_count));
    for _ in 0..event_count {
        let timestamp = reader.u64()?;
        let x_micropixels = reader.i64()?;
        let y_micropixels = reader.i64()?;
        let flags = reader.u8()?;
        if flags & !0b11 != 0 {
            return Err(DashError::InvalidCursorPayload);
        }
        let bitmap_id = reader.u64()?;
        let bitmap = if flags & (1 << 1) != 0 {
            let width = reader.u32()?;
            let height = reader.u32()?;
            let hotspot_x = reader.i32()?;
            let hotspot_y = reader.i32()?;
            let rgba_len =
                usize::try_from(reader.u32()?).map_err(|_| DashError::InvalidCursorPayload)?;
            Some(CursorBitmap {
                width,
                height,
                hotspot_x,
                hotspot_y,
                rgba: reader.take(rgba_len)?.to_vec(),
            })
        } else {
            None
        };
        events.push(CursorEvent {
            timestamp,
            x_micropixels,
            y_micropixels,
            visible: flags & 1 != 0,
            bitmap_id,
            bitmap,
        });
    }
    if !reader.is_empty() {
        return Err(DashError::InvalidCursorPayload);
    }
    Ok(CursorBatch {
        source_width,
        source_height,
        events,
    })
}

struct CursorReader<'a> {
    bytes: &'a [u8],
    offset: usize,
}

impl<'a> CursorReader<'a> {
    fn new(bytes: &'a [u8]) -> Self {
        Self { bytes, offset: 0 }
    }

    fn take(&mut self, length: usize) -> Result<&'a [u8]> {
        let end = self
            .offset
            .checked_add(length)
            .ok_or(DashError::InvalidCursorPayload)?;
        let value = self
            .bytes
            .get(self.offset..end)
            .ok_or(DashError::InvalidCursorPayload)?;
        self.offset = end;
        Ok(value)
    }

    fn u8(&mut self) -> Result<u8> {
        Ok(self.take(1)?[0])
    }

    fn u16(&mut self) -> Result<u16> {
        Ok(u16::from_be_bytes(
            self.take(2)?
                .try_into()
                .map_err(|_| DashError::InvalidCursorPayload)?,
        ))
    }

    fn u32(&mut self) -> Result<u32> {
        Ok(u32::from_be_bytes(
            self.take(4)?
                .try_into()
                .map_err(|_| DashError::InvalidCursorPayload)?,
        ))
    }

    fn i32(&mut self) -> Result<i32> {
        Ok(i32::from_be_bytes(
            self.take(4)?
                .try_into()
                .map_err(|_| DashError::InvalidCursorPayload)?,
        ))
    }

    fn u64(&mut self) -> Result<u64> {
        Ok(u64::from_be_bytes(
            self.take(8)?
                .try_into()
                .map_err(|_| DashError::InvalidCursorPayload)?,
        ))
    }

    fn i64(&mut self) -> Result<i64> {
        Ok(i64::from_be_bytes(
            self.take(8)?
                .try_into()
                .map_err(|_| DashError::InvalidCursorPayload)?,
        ))
    }

    fn is_empty(&self) -> bool {
        self.offset == self.bytes.len()
    }

    fn remaining(&self) -> usize {
        self.bytes.len().saturating_sub(self.offset)
    }
}

fn validate_cursor_batch(batch: &CursorBatch) -> Result<()> {
    if batch.source_width == 0
        || batch.source_height == 0
        || batch.source_width > u32::from(u16::MAX)
        || batch.source_height > u32::from(u16::MAX)
        || batch.events.is_empty()
    {
        return Err(DashError::InvalidCursorPayload);
    }
    let max_x = i64::from(batch.source_width)
        .checked_mul(1_000_000)
        .ok_or(DashError::InvalidCursorPayload)?;
    let max_y = i64::from(batch.source_height)
        .checked_mul(1_000_000)
        .ok_or(DashError::InvalidCursorPayload)?;
    let mut previous_timestamp = None;
    for event in &batch.events {
        if previous_timestamp.is_some_and(|previous| event.timestamp < previous) {
            return Err(DashError::InvalidCursorPayload);
        }
        previous_timestamp = Some(event.timestamp);
        if event.visible {
            if !(0..=max_x).contains(&event.x_micropixels)
                || !(0..=max_y).contains(&event.y_micropixels)
            {
                return Err(DashError::InvalidCursorPayload);
            }
        } else if event.x_micropixels != 0 || event.y_micropixels != 0 || event.bitmap.is_some() {
            return Err(DashError::InvalidCursorPayload);
        }
        if let Some(bitmap) = &event.bitmap {
            if event.bitmap_id == 0
                || bitmap.width == 0
                || bitmap.height == 0
                || bitmap.width > MAX_CURSOR_BITMAP_SIDE
                || bitmap.height > MAX_CURSOR_BITMAP_SIDE
                || bitmap.hotspot_x < 0
                || bitmap.hotspot_y < 0
                // Compared in the unsigned space rather than casting the side
                // down to it. The clauses above already rejected a negative
                // hotspot, so widening it is exact, where narrowing the side
                // would depend on a bound that lives elsewhere.
                || bitmap.hotspot_x.unsigned_abs() >= bitmap.width
                || bitmap.hotspot_y.unsigned_abs() >= bitmap.height
            {
                return Err(DashError::InvalidCursorPayload);
            }
            let expected = usize::try_from(bitmap.width)
                .ok()
                .and_then(|width| {
                    usize::try_from(bitmap.height)
                        .ok()
                        .and_then(|height| width.checked_mul(height))
                })
                .and_then(|pixels| pixels.checked_mul(4));
            if expected != Some(bitmap.rgba.len()) {
                return Err(DashError::InvalidCursorPayload);
            }
        }
    }
    cursor_batch_encoded_len(batch)?;
    Ok(())
}

fn validate_cursor_context(batch: &CursorBatch, context: CursorContext) -> Result<()> {
    if context.stream_id.is_nil()
        || context.epoch_id.is_nil()
        || batch.source_width != context.source_width
        || batch.source_height != context.source_height
        || batch.events.first().map(|event| event.timestamp) != Some(context.start_timestamp)
    {
        return Err(DashError::InvalidCursorPayload);
    }
    Ok(())
}

fn cursor_batch_encoded_len(batch: &CursorBatch) -> Result<usize> {
    u16::try_from(batch.events.len()).map_err(|_| DashError::CursorTooLarge)?;
    let mut length = CURSOR_BATCH_HEADER_LEN;
    for event in &batch.events {
        length = length
            .checked_add(CURSOR_EVENT_LEN)
            .ok_or(DashError::CursorTooLarge)?;
        if let Some(bitmap) = &event.bitmap {
            length = length
                .checked_add(CURSOR_BITMAP_HEADER_LEN)
                .and_then(|length| length.checked_add(bitmap.rgba.len()))
                .ok_or(DashError::CursorTooLarge)?;
        }
        if length > MAX_CURSOR_PLAINTEXT {
            return Err(DashError::CursorTooLarge);
        }
    }
    Ok(length)
}

fn validate_encrypted_cursor_batch(encrypted: &EncryptedCursorBatch) -> Result<()> {
    if encrypted.ciphertext.len() < AES_GCM_TAG_LEN {
        return Err(DashError::InvalidCursorPayload);
    }
    if encrypted
        .ciphertext
        .len()
        .saturating_add(ENCRYPTED_CURSOR_HEADER_LEN)
        > MAX_CURSOR_PAYLOAD
    {
        return Err(DashError::CursorTooLarge);
    }
    Ok(())
}

fn cursor_aad(context: CursorContext) -> Vec<u8> {
    let mut aad = Vec::with_capacity(16 + 16 + 8 + 8 + 4 + 4 + 16);
    aad.extend_from_slice(b"glacial-cursor-v1");
    aad.extend_from_slice(context.stream_id.as_bytes());
    aad.extend_from_slice(context.epoch_id.as_bytes());
    aad.extend_from_slice(&context.sequence.to_be_bytes());
    aad.extend_from_slice(&context.start_timestamp.to_be_bytes());
    aad.extend_from_slice(&context.source_width.to_be_bytes());
    aad.extend_from_slice(&context.source_height.to_be_bytes());
    aad
}

#[derive(Debug, Clone)]
/// H.264 decoder configuration used to build an encrypted initialization segment.
pub struct AvcConfig {
    /// Encoded width in pixels.
    pub width: u16,
    /// Encoded height in pixels.
    pub height: u16,
    /// Sequence parameter set without an Annex-B start code.
    pub sps: Vec<u8>,
    /// Picture parameter set without an Annex-B start code.
    pub pps: Vec<u8>,
}

impl AvcConfig {
    /// Returns the RFC 6381 codec string derived from the SPS profile bytes.
    pub fn codec_string(&self) -> Result<String> {
        if self.sps.len() < 4 {
            return Err(DashError::InvalidSps);
        }
        Ok(format!(
            "avc1.{:02x}{:02x}{:02x}",
            self.sps[1], self.sps[2], self.sps[3]
        ))
    }
}

#[derive(Debug, Clone)]
/// Input for one independently emitted encrypted fMP4 video fragment.
pub struct FragmentInput<'a> {
    /// MP4 fragment sequence number.
    pub sequence: u32,
    /// Base media decode time in [`MEDIA_TIMESCALE`] ticks.
    pub decode_time: u64,
    /// Sample duration in [`MEDIA_TIMESCALE`] ticks.
    pub duration: u32,
    /// Whether the access unit is a random-access point.
    pub keyframe: bool,
    /// H.264 access unit using three- or four-byte Annex-B start codes.
    pub annex_b: &'a [u8],
    /// Unique per-sample CENC AES-CTR initialization vector.
    pub iv: [u8; 16],
}

#[derive(Debug, Clone, PartialEq, Eq)]
/// Complete fMP4 fragment plus its encrypted sample and CENC layout metadata.
pub struct MediaFragment {
    /// Serialized `moof` followed by `mdat`, ready for MSE append.
    pub bytes: Vec<u8>,
    /// Length-prefixed encrypted AVC sample stored inside `bytes`.
    pub encrypted_sample: Vec<u8>,
    /// Clear/encrypted ranges declared in CENC auxiliary information.
    pub subsamples: Vec<Subsample>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// One CENC subsample pair for an AVC NAL unit.
pub struct Subsample {
    /// Clear bytes containing the NAL length and header.
    pub clear_bytes: u16,
    /// Following bytes encrypted with AES-128-CTR.
    pub encrypted_bytes: u32,
}

/// Builds an AVC/CENC fragmented-MP4 initialization segment.
pub fn build_init_segment(config: &AvcConfig, key_id: Option<[u8; 16]>) -> Result<Vec<u8>> {
    // Both bounds matter. `avcC` gives each parameter set a 16-bit length, so a
    // longer one would be written with a truncated prefix and the segment would
    // describe a different set of bytes than it carries -- silently, and only
    // for the decoder to trip over. Real parameter sets are tens of bytes; this
    // is here because the encoder hands these over and nothing else checks.
    if config.sps.len() < 4 || config.sps.len() > u16::MAX as usize {
        return Err(DashError::InvalidSps);
    }
    if config.pps.is_empty() || config.pps.len() > u16::MAX as usize {
        return Err(DashError::InvalidPps);
    }

    let ftyp = mp4_box(*b"ftyp", |out| {
        out.extend_from_slice(b"iso6");
        put_u32(out, 1);
        out.extend_from_slice(b"iso6");
        out.extend_from_slice(b"dash");
        out.extend_from_slice(b"cmfc");
        out.extend_from_slice(b"mp41");
    });

    let moov = mp4_box(*b"moov", |moov| {
        moov.extend(full_box(*b"mvhd", 0, 0, |out| {
            put_u32(out, 0);
            put_u32(out, 0);
            put_u32(out, MEDIA_TIMESCALE);
            put_u32(out, 0);
            put_u32(out, 0x0001_0000);
            put_u16(out, 0x0100);
            put_u16(out, 0);
            out.extend_from_slice(&[0; 8]);
            write_unity_matrix(out);
            out.extend_from_slice(&[0; 24]);
            put_u32(out, 2);
        }));
        moov.extend(build_track(config, key_id));
        moov.extend(mp4_box(*b"mvex", |out| {
            out.extend(full_box(*b"trex", 0, 0, |trex| {
                put_u32(trex, 1);
                put_u32(trex, 1);
                put_u32(trex, DEFAULT_FRAME_DURATION);
                put_u32(trex, 0);
                put_u32(trex, 0);
            }));
        }));
    });

    let mut output = Vec::with_capacity(ftyp.len() + moov.len());
    output.extend(ftyp);
    output.extend(moov);
    Ok(output)
}

fn build_track(config: &AvcConfig, key_id: Option<[u8; 16]>) -> Vec<u8> {
    mp4_box(*b"trak", |trak| {
        trak.extend(full_box(*b"tkhd", 0, 0x000007, |out| {
            put_u32(out, 0);
            put_u32(out, 0);
            put_u32(out, 1);
            put_u32(out, 0);
            put_u32(out, 0);
            out.extend_from_slice(&[0; 8]);
            put_u16(out, 0);
            put_u16(out, 0);
            put_u16(out, 0);
            put_u16(out, 0);
            write_unity_matrix(out);
            put_u32(out, u32::from(config.width) << 16);
            put_u32(out, u32::from(config.height) << 16);
        }));
        trak.extend(mp4_box(*b"mdia", |mdia| {
            mdia.extend(full_box(*b"mdhd", 0, 0, |out| {
                put_u32(out, 0);
                put_u32(out, 0);
                put_u32(out, MEDIA_TIMESCALE);
                put_u32(out, 0);
                put_u16(out, 0x55c4);
                put_u16(out, 0);
            }));
            mdia.extend(full_box(*b"hdlr", 0, 0, |out| {
                put_u32(out, 0);
                out.extend_from_slice(b"vide");
                out.extend_from_slice(&[0; 12]);
                out.extend_from_slice(b"GlacialCast Video\0");
            }));
            mdia.extend(mp4_box(*b"minf", |minf| {
                minf.extend(full_box(*b"vmhd", 0, 1, |out| {
                    out.extend_from_slice(&[0; 8]);
                }));
                minf.extend(mp4_box(*b"dinf", |dinf| {
                    dinf.extend(full_box(*b"dref", 0, 0, |out| {
                        put_u32(out, 1);
                        out.extend(full_box(*b"url ", 0, 1, |_| {}));
                    }));
                }));
                minf.extend(build_sample_table(config, key_id));
            }));
        }));
    })
}

fn build_sample_table(config: &AvcConfig, key_id: Option<[u8; 16]>) -> Vec<u8> {
    mp4_box(*b"stbl", |stbl| {
        stbl.extend(full_box(*b"stsd", 0, 0, |out| {
            put_u32(out, 1);
            out.extend(build_sample_entry(config, key_id));
        }));
        stbl.extend(full_box(*b"stts", 0, 0, |out| put_u32(out, 0)));
        stbl.extend(full_box(*b"stsc", 0, 0, |out| put_u32(out, 0)));
        stbl.extend(full_box(*b"stsz", 0, 0, |out| {
            put_u32(out, 0);
            put_u32(out, 0);
        }));
        stbl.extend(full_box(*b"stco", 0, 0, |out| put_u32(out, 0)));
    })
}

/// # Invariants
///
/// `config.sps` and `config.pps` must each fit in a `u16`, which is what
/// `build_encrypted_init_segment` checks before calling this. The `avcC` box
/// gives each a 16-bit length, so a longer one would be written with a
/// truncated prefix.
#[allow(
    clippy::cast_possible_truncation,
    reason = "parameter-set lengths are bounded to u16 by the caller, per the invariant above"
)]
fn build_sample_entry(config: &AvcConfig, key_id: Option<[u8; 16]>) -> Vec<u8> {
    // A protected track declares `encv` and carries the scheme in `sinf`; an
    // unprotected one is plain `avc1` with neither. Emitting `encv` without a
    // scheme, or `avc1` with one, describes a track that is not what it says.
    let kind = if key_id.is_some() { *b"encv" } else { *b"avc1" };
    mp4_box(kind, |entry| {
        entry.extend_from_slice(&[0; 6]);
        put_u16(entry, 1);
        entry.extend_from_slice(&[0; 16]);
        put_u16(entry, config.width);
        put_u16(entry, config.height);
        put_u32(entry, 0x0048_0000);
        put_u32(entry, 0x0048_0000);
        put_u32(entry, 0);
        put_u16(entry, 1);
        entry.extend_from_slice(&[0; 32]);
        put_u16(entry, 0x0018);
        put_u16(entry, u16::MAX);

        entry.extend(mp4_box(*b"avcC", |avcc| {
            avcc.push(1);
            avcc.push(config.sps[1]);
            avcc.push(config.sps[2]);
            avcc.push(config.sps[3]);
            avcc.push(0xff);
            avcc.push(0xe1);
            put_u16(avcc, config.sps.len() as u16);
            avcc.extend_from_slice(&config.sps);
            avcc.push(1);
            put_u16(avcc, config.pps.len() as u16);
            avcc.extend_from_slice(&config.pps);
        }));

        if let Some(key_id) = key_id {
            entry.extend(mp4_box(*b"sinf", |sinf| {
                sinf.extend(mp4_box(*b"frma", |out| out.extend_from_slice(b"avc1")));
                sinf.extend(full_box(*b"schm", 0, 0, |out| {
                    out.extend_from_slice(b"cenc");
                    put_u32(out, 0x0001_0000);
                }));
                sinf.extend(mp4_box(*b"schi", |schi| {
                    schi.extend(full_box(*b"tenc", 0, 0, |out| {
                        out.push(0);
                        out.push(0);
                        out.push(1);
                        out.push(16);
                        out.extend_from_slice(&key_id);
                    }));
                }));
            }));
        }
    })
}

/// Converts one Annex-B access unit into an immediately appendable CENC fMP4 fragment.
#[allow(
    clippy::cast_possible_truncation,
    reason = "sample lengths are bounded by MAX_MEDIA_PAYLOAD, and the saiz and \
              senc fields by the AuxiliaryInfoTooLarge check below"
)]
pub fn build_fragment(
    cenc_key: Option<&[u8; 16]>,
    input: FragmentInput<'_>,
) -> Result<MediaFragment> {
    if input.annex_b.len() > MAX_MEDIA_PAYLOAD {
        return Err(DashError::MediaTooLarge);
    }
    let (mut sample, ranges) = annex_b_to_avcc(input.annex_b)?;
    // Without a key the sample stays as it is and describes no subsamples, so
    // the protection boxes below are omitted rather than written empty: a
    // `saiz`/`saio`/`senc` trio saying nothing is protected is a claim about
    // encryption that an unencrypted fragment should not be making.
    let mut subsamples = Vec::with_capacity(ranges.len());
    if let Some(cenc_key) = cenc_key {
        let mut cipher = Aes128Ctr::new(cenc_key.into(), (&input.iv).into());
        for range in ranges {
            let clear_bytes = 5u16;
            let encrypted_len = range.end.saturating_sub(range.start);
            cipher.apply_keystream(&mut sample[range]);
            subsamples.push(Subsample {
                clear_bytes,
                encrypted_bytes: encrypted_len as u32,
            });
        }
    }

    let auxiliary_size = 16usize
        .saturating_add(2)
        .saturating_add(subsamples.len().saturating_mul(6));
    if auxiliary_size > u8::MAX as usize || subsamples.len() > u16::MAX as usize {
        return Err(DashError::AuxiliaryInfoTooLarge);
    }

    let mut moof = mp4_box(*b"moof", |moof| {
        moof.extend(full_box(*b"mfhd", 0, 0, |out| {
            put_u32(out, input.sequence);
        }));
        moof.extend(mp4_box(*b"traf", |traf| {
            traf.extend(full_box(*b"tfhd", 0, 0x020000, |out| {
                put_u32(out, 1);
            }));
            traf.extend(full_box(*b"tfdt", 1, 0, |out| {
                put_u64(out, input.decode_time);
            }));
            traf.extend(full_box(*b"trun", 0, 0x000701, |out| {
                put_u32(out, 1);
                put_i32(out, 0);
                put_u32(out, input.duration);
                put_u32(out, sample.len() as u32);
                put_u32(
                    out,
                    if input.keyframe {
                        0x0200_0000
                    } else {
                        0x0101_0000
                    },
                );
            }));
            if cenc_key.is_some() {
                traf.extend(full_box(*b"saiz", 0, 0, |out| {
                    out.push(auxiliary_size as u8);
                    put_u32(out, 1);
                }));
                traf.extend(full_box(*b"saio", 0, 0, |out| {
                    put_u32(out, 1);
                    put_u32(out, 0);
                }));
                traf.extend(full_box(*b"senc", 0, 0x000002, |out| {
                    put_u32(out, 1);
                    out.extend_from_slice(&input.iv);
                    put_u16(out, subsamples.len() as u16);
                    for subsample in &subsamples {
                        put_u16(out, subsample.clear_bytes);
                        put_u32(out, subsample.encrypted_bytes);
                    }
                }));
            }
        }));
    });

    if cenc_key.is_some() {
        patch_fragment_offsets(&mut moof)?;
    } else {
        patch_data_offset(&mut moof)?;
    }
    let mdat = mp4_box(*b"mdat", |out| out.extend_from_slice(&sample));
    let mut bytes = Vec::with_capacity(moof.len() + mdat.len());
    bytes.extend_from_slice(&moof);
    bytes.extend_from_slice(&mdat);

    Ok(MediaFragment {
        bytes,
        encrypted_sample: sample,
        subsamples,
    })
}

/// Points `trun` at the sample data, which every fragment needs.
///
/// The offset is relative to the start of the `moof`, which is what
/// `default-base-is-moof` in `tfhd` selects, and the `mdat` payload begins
/// eight bytes past its end.
fn patch_data_offset(moof: &mut [u8]) -> Result<()> {
    let trun = find_box(moof, *b"trun").ok_or(DashError::EmptyAccessUnit)?;
    let data_offset = i32::try_from(moof.len() + 8).map_err(|_| DashError::MediaTooLarge)?;
    moof[trun + 16..trun + 20].copy_from_slice(&data_offset.to_be_bytes());
    Ok(())
}

/// Points `trun` at the sample data and `saio` at the per-sample encryption
/// information, for a protected fragment.
fn patch_fragment_offsets(moof: &mut [u8]) -> Result<()> {
    patch_data_offset(moof)?;

    let saio = find_box(moof, *b"saio").ok_or(DashError::EmptyAccessUnit)?;
    let senc = find_box(moof, *b"senc").ok_or(DashError::EmptyAccessUnit)?;
    let auxiliary_offset = u32::try_from(senc + 16).map_err(|_| DashError::MediaTooLarge)?;
    moof[saio + 16..saio + 20].copy_from_slice(&auxiliary_offset.to_be_bytes());
    Ok(())
}

#[allow(
    clippy::cast_possible_truncation,
    reason = "each NAL is part of a total already refused above MAX_MEDIA_PAYLOAD, \
              which is far below u32::MAX"
)]
fn annex_b_to_avcc(access_unit: &[u8]) -> Result<(Vec<u8>, Vec<std::ops::Range<usize>>)> {
    let nals = annex_b_nals(access_unit);
    if nals.is_empty() {
        return Err(DashError::EmptyAccessUnit);
    }
    let total = nals
        .iter()
        .fold(0usize, |sum, nal| sum.saturating_add(4 + nal.len()));
    if total > MAX_MEDIA_PAYLOAD {
        return Err(DashError::MediaTooLarge);
    }
    let mut sample = Vec::with_capacity(total);
    let mut encrypted_ranges = Vec::with_capacity(nals.len());
    for nal in nals {
        put_u32(&mut sample, nal.len() as u32);
        sample.extend_from_slice(nal);
        // Every NAL needs an entry, including one too short to hold any
        // encrypted bytes. CENC defines a sample by its subsample table, so an
        // entry left out does not make that NAL clear -- it makes the table
        // stop short of the sample, and a decoder has no defined way to read
        // the remainder. A one-byte NAL yields an empty encrypted range, which
        // is five clear bytes and nothing protected.
        if !nal.is_empty() {
            let start = sample.len() - nal.len() + 1;
            encrypted_ranges.push(start.min(sample.len())..sample.len());
        }
    }
    Ok((sample, encrypted_ranges))
}

fn annex_b_nals(access_unit: &[u8]) -> Vec<&[u8]> {
    let mut starts = Vec::new();
    let mut cursor = 0usize;
    while cursor + 3 <= access_unit.len() {
        if access_unit[cursor..].starts_with(&[0, 0, 1]) {
            starts.push((cursor, 3));
            cursor += 3;
        } else if access_unit[cursor..].starts_with(&[0, 0, 0, 1]) {
            starts.push((cursor, 4));
            cursor += 4;
        } else {
            cursor += 1;
        }
    }
    starts
        .iter()
        .enumerate()
        .filter_map(|(index, (start, prefix))| {
            let begin = start + prefix;
            let end = starts
                .get(index + 1)
                .map(|(next, _)| *next)
                .unwrap_or(access_unit.len());
            (begin < end).then_some(&access_unit[begin..end])
        })
        .collect()
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
/// One numbered media segment in an MPD `SegmentTimeline`.
pub struct SegmentTimelineEntry {
    /// Segment number used to expand `$Number$` in the media URL.
    pub number: u64,
    /// Segment start in [`MEDIA_TIMESCALE`] ticks.
    pub start: u64,
    /// Segment duration in [`MEDIA_TIMESCALE`] ticks.
    pub duration: u64,
}

#[derive(Debug, Clone)]
/// Inputs for GlacialCast's constrained live or static MPEG-DASH manifest.
pub struct MpdConfig<'a> {
    /// Durable stream identity written into the MPD period identifier.
    pub stream_id: Uuid,
    /// Epoch used in initialization and media URLs.
    pub epoch_id: Uuid,
    /// CENC default key identifier advertised to EME.
    pub key_id: [u8; 16],
    /// Encoded video width in pixels.
    pub width: u16,
    /// Encoded video height in pixels.
    pub height: u16,
    /// RFC 6381 AVC codec string.
    pub codec: &'a str,
    /// RFC 3339 availability start time for a dynamic presentation.
    pub availability_start_time: &'a str,
    /// Retained live-history duration advertised by a dynamic MPD.
    pub time_shift_buffer_depth_seconds: u64,
    /// Ordered available segment timeline.
    pub segments: &'a [SegmentTimelineEntry],
    /// Whether to emit a dynamic live MPD instead of a finalized static MPD.
    pub dynamic: bool,
}

/// Builds the XML MPD for the supplied constrained GlacialCast presentation.
pub fn build_mpd(config: &MpdConfig<'_>) -> String {
    let mpd_type = if config.dynamic { "dynamic" } else { "static" };
    let first_timestamp = config.segments.first().map_or(0, |segment| segment.start);
    let presentation_end = config.segments.last().map_or(first_timestamp, |segment| {
        segment.start.saturating_add(segment.duration)
    });
    let timing_attributes = if config.dynamic {
        format!(
            "availabilityStartTime=\"{}\" timeShiftBufferDepth=\"PT{}S\" \
             minimumUpdatePeriod=\"PT1S\" suggestedPresentationDelay=\"PT2S\"",
            xml_escape(config.availability_start_time),
            config.time_shift_buffer_depth_seconds
        )
    } else {
        format!(
            "mediaPresentationDuration=\"PT{:.3}S\"",
            presentation_end.saturating_sub(first_timestamp) as f64 / f64::from(MEDIA_TIMESCALE)
        )
    };
    let presentation_time_offset = if config.dynamic {
        String::new()
    } else {
        format!(" presentationTimeOffset=\"{first_timestamp}\"")
    };
    let mut xml = format!(
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
         <MPD xmlns=\"urn:mpeg:dash:schema:mpd:2011\" \
         xmlns:cenc=\"urn:mpeg:cenc:2013\" \
         profiles=\"urn:mpeg:dash:profile:isoff-live:2011\" \
         type=\"{mpd_type}\" {timing_attributes} minBufferTime=\"PT1S\">\n\
         <Period id=\"{}\" start=\"PT0S\">\n\
         <AdaptationSet id=\"1\" contentType=\"video\" mimeType=\"video/mp4\" \
         segmentAlignment=\"true\" startWithSAP=\"1\">\n\
         <ContentProtection schemeIdUri=\"urn:mpeg:dash:mp4protection:2011\" \
         value=\"cenc\" cenc:default_KID=\"{}\"/>\n\
         <Representation id=\"video\" bandwidth=\"1000000\" codecs=\"{}\" \
         width=\"{}\" height=\"{}\">\n\
         <SegmentTemplate timescale=\"{}\" startNumber=\"{}\"{presentation_time_offset} \
         initialization=\"epochs/{}/init.mp4\" \
         media=\"epochs/{}/media/$Number$.m4s\">\n\
         <SegmentTimeline>\n",
        config.stream_id,
        format_uuid(config.key_id),
        xml_escape(config.codec),
        config.width,
        config.height,
        MEDIA_TIMESCALE,
        config
            .segments
            .first()
            .map(|segment| segment.number)
            .unwrap_or(1),
        config.epoch_id,
        config.epoch_id,
    );
    for segment in config.segments {
        let _ = writeln!(
            xml,
            "<S t=\"{}\" d=\"{}\"/>",
            segment.start, segment.duration
        );
    }
    xml.push_str(
        "</SegmentTimeline>\n</SegmentTemplate>\n</Representation>\n\
         </AdaptationSet>\n</Period>\n</MPD>\n",
    );
    xml
}

/// Computes the HMAC-SHA-256 tag over canonical header bytes and opaque payload.
pub fn authenticate_object(
    authentication_key: &[u8; 32],
    header: &[u8],
    payload: &[u8],
) -> [u8; 32] {
    let mut mac =
        <HmacSha256 as Mac>::new_from_slice(authentication_key).expect("HMAC accepts any key");
    mac.update(header);
    mac.update(payload);
    mac.finalize().into_bytes().into()
}

/// Verifies an object authentication tag in constant time.
pub fn verify_object_authentication(
    authentication_key: &[u8; 32],
    header: &[u8],
    payload: &[u8],
    tag: &[u8; 32],
) -> bool {
    let mut mac =
        <HmacSha256 as Mac>::new_from_slice(authentication_key).expect("HMAC accepts any key");
    mac.update(header);
    mac.update(payload);
    mac.verify_slice(tag).is_ok()
}

fn mp4_box(kind: [u8; 4], build: impl FnOnce(&mut Vec<u8>)) -> Vec<u8> {
    let mut output = Vec::new();
    output.extend_from_slice(&[0; 4]);
    output.extend_from_slice(&kind);
    build(&mut output);
    let size = u32::try_from(output.len()).expect("MVP MP4 box must fit in 32 bits");
    output[..4].copy_from_slice(&size.to_be_bytes());
    output
}

fn full_box(kind: [u8; 4], version: u8, flags: u32, build: impl FnOnce(&mut Vec<u8>)) -> Vec<u8> {
    mp4_box(kind, |out| {
        out.push(version);
        out.extend_from_slice(&flags.to_be_bytes()[1..]);
        build(out);
    })
}

fn find_box(bytes: &[u8], kind: [u8; 4]) -> Option<usize> {
    bytes
        .windows(4)
        .position(|window| window == kind)
        .and_then(|kind_offset| kind_offset.checked_sub(4))
}

fn put_u16(out: &mut Vec<u8>, value: u16) {
    out.extend_from_slice(&value.to_be_bytes());
}

fn put_u32(out: &mut Vec<u8>, value: u32) {
    out.extend_from_slice(&value.to_be_bytes());
}

fn put_i32(out: &mut Vec<u8>, value: i32) {
    out.extend_from_slice(&value.to_be_bytes());
}

fn put_u64(out: &mut Vec<u8>, value: u64) {
    out.extend_from_slice(&value.to_be_bytes());
}

fn write_unity_matrix(out: &mut Vec<u8>) {
    for value in [0x0001_0000u32, 0, 0, 0, 0x0001_0000, 0, 0, 0, 0x4000_0000] {
        put_u32(out, value);
    }
}

fn format_uuid(bytes: [u8; 16]) -> String {
    Uuid::from_bytes(bytes).hyphenated().to_string()
}

fn xml_escape(value: &str) -> String {
    value
        .replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&apos;")
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_config() -> AvcConfig {
        AvcConfig {
            width: 1280,
            height: 720,
            sps: vec![0x67, 0x42, 0xc0, 0x1f, 0xda, 0x01, 0x40, 0x16],
            pps: vec![0x68, 0xce, 0x06, 0xe2],
        }
    }

    fn cursor_fixture() -> CursorBatch {
        CursorBatch {
            source_width: 320,
            source_height: 180,
            events: vec![
                CursorEvent {
                    timestamp: 100,
                    x_micropixels: 1_500_000,
                    y_micropixels: 250_000,
                    visible: true,
                    bitmap_id: 9,
                    bitmap: Some(CursorBitmap {
                        width: 2,
                        height: 1,
                        hotspot_x: 1,
                        hotspot_y: 0,
                        rgba: vec![1, 2, 3, 4, 5, 6, 7, 8],
                    }),
                },
                CursorEvent {
                    timestamp: 200,
                    x_micropixels: 0,
                    y_micropixels: 0,
                    visible: false,
                    bitmap_id: 9,
                    bitmap: None,
                },
            ],
        }
    }

    fn cursor_context(batch: &CursorBatch) -> CursorContext {
        CursorContext {
            stream_id: Uuid::from_u128(1),
            epoch_id: Uuid::from_u128(2),
            sequence: 4,
            start_timestamp: batch.events[0].timestamp,
            source_width: batch.source_width,
            source_height: batch.source_height,
        }
    }

    #[test]
    fn an_unencrypted_fragment_carries_no_protection_and_no_ciphertext() {
        let access_unit: &[u8] = &[
            0, 0, 0, 1, 0x65, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 1, 0x06, 9, 10, 11,
        ];
        let input = || FragmentInput {
            sequence: 1,
            decode_time: 0,
            duration: 90_000,
            keyframe: true,
            annex_b: access_unit,
            iv: [5u8; 16],
        };
        let plain = build_fragment(None, input()).unwrap();
        let sealed = build_fragment(Some(&[4u8; 16]), input()).unwrap();

        // No key means no claim about encryption: the boxes that describe
        // per-sample protection must be absent, not present and empty.
        for box_kind in [b"saiz", b"saio", b"senc"] {
            assert!(
                find_box(&plain.bytes, *box_kind).is_none(),
                "unencrypted fragment must not carry {}",
                std::str::from_utf8(box_kind).unwrap()
            );
            assert!(
                find_box(&sealed.bytes, *box_kind).is_some(),
                "encrypted fragment must still carry {}",
                std::str::from_utf8(box_kind).unwrap()
            );
        }
        assert!(plain.subsamples.is_empty());

        // The payload really is in the clear: the NAL body survives verbatim,
        // where the encrypted build leaves it changed.
        assert!(
            plain
                .encrypted_sample
                .windows(8)
                .any(|w| w == [1, 2, 3, 4, 5, 6, 7, 8]),
            "unencrypted sample must contain the original NAL body"
        );
        assert!(
            !sealed
                .encrypted_sample
                .windows(8)
                .any(|w| w == [1, 2, 3, 4, 5, 6, 7, 8]),
            "encrypted sample must not"
        );
        // Both still point trun at the sample data.
        assert!(find_box(&plain.bytes, *b"trun").is_some());
    }

    #[test]
    fn an_unencrypted_init_segment_declares_a_plain_avc_track() {
        let plain = build_init_segment(&fixture_config(), None).unwrap();
        let sealed = build_init_segment(&fixture_config(), Some([3u8; 16])).unwrap();
        // `encv` plus `sinf` is the protected shape; `avc1` with neither is the
        // plain one. A track that says `encv` and carries no scheme, or says
        // `avc1` and carries one, describes something it is not.
        assert!(find_box(&plain, *b"avc1").is_some());
        assert!(find_box(&plain, *b"encv").is_none());
        assert!(find_box(&plain, *b"sinf").is_none());
        assert!(find_box(&plain, *b"tenc").is_none());
        assert!(find_box(&sealed, *b"encv").is_some());
        assert!(find_box(&sealed, *b"sinf").is_some());
        // The decoder configuration is the same either way.
        assert!(find_box(&plain, *b"avcC").is_some());
    }

    #[test]
    fn a_descriptor_without_the_flag_still_reads_as_encrypted() {
        // Objects retained from before the field existed must keep working:
        // absent means encrypted, because that is the only thing it could have
        // been. Written as raw JSON rather than by round-tripping a struct,
        // since the point is what an older publisher actually wrote.
        let epoch = Uuid::new_v4();
        let stream = Uuid::new_v4();
        let legacy = serde_json::json!({
            "format_version": DASH_FORMAT_VERSION,
            "stream_id": stream,
            "epoch_id": epoch,
            "key_id": epoch.as_bytes(),
            "width": 1920,
            "height": 1080,
            "codec": "avc1.42c028",
            "timescale": MEDIA_TIMESCALE,
            "segment_frames": 5,
            "availability_start_time": "2026-01-01T00:00:00.000Z",
        });
        let parsed = EpochDescriptor::from_json(&serde_json::to_vec(&legacy).unwrap())
            .expect("a descriptor predating the flag must still parse");
        assert!(parsed.encrypted, "absent must mean encrypted");

        // And the flag survives a round trip once it is written.
        let mut plain = parsed.clone();
        plain.encrypted = false;
        let reparsed = EpochDescriptor::from_json(&plain.to_json().unwrap()).unwrap();
        assert!(!reparsed.encrypted);
    }

    #[test]
    fn epoch_keys_are_stable_and_scoped() {
        let viewer_key = [7u8; 32];
        let stream = Uuid::from_u128(1);
        let epoch = Uuid::from_u128(2);
        let first = EpochKeys::derive(&viewer_key, stream, epoch).unwrap();
        let second = EpochKeys::derive(&viewer_key, stream, epoch).unwrap();
        let other = EpochKeys::derive(&viewer_key, stream, Uuid::from_u128(3)).unwrap();

        assert_eq!(first, second);
        assert_ne!(first.cenc_key, other.cenc_key);
        assert_eq!(first.key_id, *epoch.as_bytes());
    }

    #[test]
    fn cursor_batch_authenticates_timing_and_dimensions() {
        let keys = EpochKeys::derive(&[9u8; 32], Uuid::from_u128(1), Uuid::from_u128(2)).unwrap();
        let context = CursorContext {
            stream_id: Uuid::from_u128(1),
            epoch_id: Uuid::from_u128(2),
            sequence: 4,
            start_timestamp: 91_500,
            source_width: 1920,
            source_height: 1080,
        };
        let batch = CursorBatch {
            source_width: 1920,
            source_height: 1080,
            events: vec![CursorEvent {
                timestamp: 91_500,
                x_micropixels: 40_500_000,
                y_micropixels: 20_250_000,
                visible: true,
                bitmap_id: 7,
                bitmap: None,
            }],
        };
        let encrypted = encrypt_cursor_batch(&keys, context, &batch).unwrap();

        assert_eq!(
            decrypt_cursor_batch(&keys, context, &encrypted).unwrap(),
            batch
        );
        let wrong_context = CursorContext {
            sequence: 5,
            ..context
        };
        assert!(decrypt_cursor_batch(&keys, wrong_context, &encrypted).is_err());
    }

    #[test]
    fn cursor_batch_binary_encoding_is_compact_and_round_trips_bitmaps() {
        let batch = cursor_fixture();
        let encoded = encode_cursor_batch(&batch).unwrap();
        assert_eq!(decode_cursor_batch(&encoded).unwrap(), batch);
        assert!(encoded.len() < serde_json::to_vec(&batch).unwrap().len());

        let encrypted = EncryptedCursorBatch {
            nonce: [7; 12],
            ciphertext: vec![8; AES_GCM_TAG_LEN],
        };
        let payload = encrypted.to_bytes().unwrap();
        assert_eq!(
            EncryptedCursorBatch::from_bytes(&payload).unwrap(),
            encrypted
        );
        assert!(EncryptedCursorBatch::from_bytes(&payload[..15]).is_err());
    }

    #[test]
    fn cursor_batch_rejects_context_mismatches_before_encryption() {
        let keys = EpochKeys::derive(&[9u8; 32], Uuid::from_u128(1), Uuid::from_u128(2)).unwrap();
        let batch = cursor_fixture();
        let context = cursor_context(&batch);

        for invalid in [
            CursorContext {
                stream_id: Uuid::nil(),
                ..context
            },
            CursorContext {
                epoch_id: Uuid::nil(),
                ..context
            },
            CursorContext {
                start_timestamp: context.start_timestamp + 1,
                ..context
            },
            CursorContext {
                source_width: context.source_width + 1,
                ..context
            },
            CursorContext {
                source_height: context.source_height + 1,
                ..context
            },
        ] {
            assert!(matches!(
                encrypt_cursor_batch(&keys, invalid, &batch),
                Err(DashError::InvalidCursorPayload)
            ));
        }
    }

    #[test]
    fn cursor_batch_rejects_invalid_timeline_and_positions() {
        let assert_invalid = |batch: CursorBatch| {
            assert!(matches!(
                validate_cursor_batch(&batch),
                Err(DashError::InvalidCursorPayload)
            ));
        };

        let mut batch = cursor_fixture();
        batch.events.clear();
        assert_invalid(batch);

        let mut batch = cursor_fixture();
        batch.events[1].timestamp = batch.events[0].timestamp - 1;
        assert_invalid(batch);

        for (x, y) in [
            (-1, 0),
            (0, -1),
            (i64::from(cursor_fixture().source_width) * 1_000_000 + 1, 0),
            (0, i64::from(cursor_fixture().source_height) * 1_000_000 + 1),
        ] {
            let mut batch = cursor_fixture();
            batch.events[0].x_micropixels = x;
            batch.events[0].y_micropixels = y;
            assert_invalid(batch);
        }

        let mut batch = cursor_fixture();
        batch.events[1].x_micropixels = 1;
        assert_invalid(batch);

        let mut batch = cursor_fixture();
        batch.events[1].bitmap = batch.events[0].bitmap.clone();
        assert_invalid(batch);

        let mut batch = cursor_fixture();
        batch.source_width = 0;
        assert_invalid(batch);

        let mut batch = cursor_fixture();
        batch.source_height = u32::from(u16::MAX) + 1;
        assert_invalid(batch);
    }

    #[test]
    fn cursor_batch_accepts_position_boundaries() {
        let mut batch = cursor_fixture();
        batch.events[0].x_micropixels = i64::from(batch.source_width) * 1_000_000;
        batch.events[0].y_micropixels = i64::from(batch.source_height) * 1_000_000;
        validate_cursor_batch(&batch).unwrap();
    }

    #[test]
    fn cursor_batch_rejects_invalid_bitmap_metadata() {
        let assert_invalid_bitmap = |mutate: fn(&mut CursorEvent, &mut CursorBitmap)| {
            let mut batch = cursor_fixture();
            let mut bitmap = batch.events[0].bitmap.take().unwrap();
            mutate(&mut batch.events[0], &mut bitmap);
            batch.events[0].bitmap = Some(bitmap);
            assert!(matches!(
                validate_cursor_batch(&batch),
                Err(DashError::InvalidCursorPayload)
            ));
        };

        assert_invalid_bitmap(|event, _| event.bitmap_id = 0);
        assert_invalid_bitmap(|_, bitmap| bitmap.width = 0);
        assert_invalid_bitmap(|_, bitmap| bitmap.height = MAX_CURSOR_BITMAP_SIDE + 1);
        assert_invalid_bitmap(|_, bitmap| bitmap.hotspot_x = -1);
        assert_invalid_bitmap(|_, bitmap| {
            bitmap.hotspot_y = i32::try_from(bitmap.height).unwrap();
        });
        assert_invalid_bitmap(|_, bitmap| {
            bitmap.rgba.pop();
        });
    }

    #[test]
    fn cursor_batch_rejects_payloads_that_exceed_encrypted_limit() {
        let rgba = vec![0; MAX_CURSOR_BITMAP_SIDE as usize * MAX_CURSOR_BITMAP_SIDE as usize * 4];
        let bitmap = CursorBitmap {
            width: MAX_CURSOR_BITMAP_SIDE,
            height: MAX_CURSOR_BITMAP_SIDE,
            hotspot_x: 0,
            hotspot_y: 0,
            rgba,
        };
        let mut batch = CursorBatch {
            source_width: 320,
            source_height: 180,
            events: Vec::new(),
        };
        for timestamp in 0..4 {
            batch.events.push(CursorEvent {
                timestamp,
                x_micropixels: 0,
                y_micropixels: 0,
                visible: true,
                bitmap_id: timestamp + 1,
                bitmap: Some(bitmap.clone()),
            });
        }
        assert!(matches!(
            validate_cursor_batch(&batch),
            Err(DashError::CursorTooLarge)
        ));
    }

    #[test]
    fn cursor_binary_decoder_rejects_all_truncations_and_trailing_data() {
        let encoded = encode_cursor_batch(&cursor_fixture()).unwrap();
        for end in 0..encoded.len() {
            assert!(
                decode_cursor_batch(&encoded[..end]).is_err(),
                "accepted cursor payload truncated at byte {end}"
            );
        }

        let mut trailing = encoded.clone();
        trailing.push(0);
        assert!(matches!(
            decode_cursor_batch(&trailing),
            Err(DashError::InvalidCursorPayload)
        ));

        let mut bad_flags = encoded;
        bad_flags[CURSOR_BATCH_HEADER_LEN + 24] = 0x80;
        assert!(matches!(
            decode_cursor_batch(&bad_flags),
            Err(DashError::InvalidCursorPayload)
        ));
    }

    #[test]
    fn cursor_binary_decoder_preflights_claimed_event_count() {
        let mut payload = Vec::from(&b"GCC1"[..]);
        payload.extend_from_slice(&320u32.to_be_bytes());
        payload.extend_from_slice(&180u32.to_be_bytes());
        payload.extend_from_slice(&u16::MAX.to_be_bytes());
        assert!(matches!(
            decode_cursor_batch(&payload),
            Err(DashError::InvalidCursorPayload)
        ));
    }

    #[test]
    fn encrypted_cursor_envelope_enforces_magic_tag_and_size() {
        let too_short = EncryptedCursorBatch {
            nonce: [0; 12],
            ciphertext: vec![0; AES_GCM_TAG_LEN - 1],
        };
        assert!(matches!(
            too_short.to_bytes(),
            Err(DashError::InvalidCursorPayload)
        ));

        let too_large = EncryptedCursorBatch {
            nonce: [0; 12],
            ciphertext: vec![0; MAX_CURSOR_PAYLOAD - ENCRYPTED_CURSOR_HEADER_LEN + 1],
        };
        assert!(matches!(
            too_large.to_bytes(),
            Err(DashError::CursorTooLarge)
        ));

        let mut wrong_magic = vec![0; ENCRYPTED_CURSOR_HEADER_LEN + AES_GCM_TAG_LEN];
        wrong_magic[..4].copy_from_slice(b"NOPE");
        assert!(matches!(
            EncryptedCursorBatch::from_bytes(&wrong_magic),
            Err(DashError::InvalidCursorPayload)
        ));
    }

    #[test]
    fn cursor_decryption_rejects_malformed_envelopes_before_crypto() {
        let batch = cursor_fixture();
        let keys = EpochKeys::derive(
            &[9u8; 32],
            cursor_context(&batch).stream_id,
            cursor_context(&batch).epoch_id,
        )
        .unwrap();
        let malformed = EncryptedCursorBatch {
            nonce: [0; 12],
            ciphertext: vec![0; AES_GCM_TAG_LEN - 1],
        };
        assert!(matches!(
            decrypt_cursor_batch(&keys, cursor_context(&batch), &malformed),
            Err(DashError::InvalidCursorPayload)
        ));
    }

    #[test]
    fn init_segment_declares_avc_and_common_encryption() {
        let init = build_init_segment(&fixture_config(), Some([3u8; 16])).unwrap();

        for marker in [
            b"ftyp", b"moov", b"encv", b"avcC", b"sinf", b"cenc", b"tenc",
        ] {
            assert!(init.windows(4).any(|window| window == marker));
        }
        assert!(init.windows(16).any(|window| window == [3u8; 16]));

        let tenc = find_box(&init, *b"tenc").unwrap();
        assert_eq!(
            &init[tenc + 8..tenc + 16],
            &[0, 0, 0, 0, 0, 0, 1, 16],
            "version/flags, reserved, pattern, protected, and IV-size fields"
        );
    }

    #[test]
    fn media_fragment_encrypts_nal_payload_but_not_length_or_header() {
        let access_unit = [
            0, 0, 0, 1, 0x65, 1, 2, 3, 4, 5, 6, 7, 8, 0, 0, 1, 0x06, 9, 10, 11,
        ];
        let fragment = build_fragment(
            Some(&[4u8; 16]),
            FragmentInput {
                sequence: 1,
                decode_time: 0,
                duration: 90_000,
                keyframe: true,
                annex_b: &access_unit,
                iv: [5u8; 16],
            },
        )
        .unwrap();

        assert_eq!(&fragment.encrypted_sample[..5], &[0, 0, 0, 9, 0x65]);
        assert_ne!(&fragment.encrypted_sample[5..13], &[1, 2, 3, 4, 5, 6, 7, 8]);
        assert_eq!(fragment.subsamples.len(), 2);
        for marker in [
            b"moof", b"traf", b"trun", b"senc", b"saiz", b"saio", b"mdat",
        ] {
            assert!(fragment.bytes.windows(4).any(|window| window == marker));
        }
    }

    #[test]
    fn mpd_declares_cenc_timeline_and_epoch_paths() {
        let stream = Uuid::from_u128(1);
        let epoch = Uuid::from_u128(2);
        let mpd = build_mpd(&MpdConfig {
            stream_id: stream,
            epoch_id: epoch,
            key_id: *epoch.as_bytes(),
            width: 1280,
            height: 720,
            codec: "avc1.42c01f",
            availability_start_time: "2026-01-01T00:00:00Z",
            time_shift_buffer_depth_seconds: 1800,
            segments: &[
                SegmentTimelineEntry {
                    number: 7,
                    start: 0,
                    duration: 360_000,
                },
                SegmentTimelineEntry {
                    number: 8,
                    start: 360_000,
                    duration: 360_000,
                },
            ],
            dynamic: true,
        });

        assert!(mpd.contains("type=\"dynamic\""));
        assert!(mpd.contains("value=\"cenc\""));
        assert!(mpd.contains(&format!("cenc:default_KID=\"{epoch}\"")));
        assert!(mpd.contains("startNumber=\"7\""));
        assert!(mpd.contains("<S t=\"360000\" d=\"360000\"/>"));

        let static_segments = [
            SegmentTimelineEntry {
                number: 7,
                start: 360_000,
                duration: 360_000,
            },
            SegmentTimelineEntry {
                number: 8,
                start: 720_000,
                duration: 360_000,
            },
        ];
        let static_mpd = build_mpd(&MpdConfig {
            stream_id: stream,
            epoch_id: epoch,
            key_id: *epoch.as_bytes(),
            width: 1280,
            height: 720,
            codec: "avc1.42c01f",
            availability_start_time: "2026-01-01T00:00:00Z",
            time_shift_buffer_depth_seconds: 1800,
            segments: &static_segments,
            dynamic: false,
        });
        assert!(static_mpd.contains("type=\"static\""));
        assert!(static_mpd.contains("mediaPresentationDuration=\"PT8.000S\""));
        assert!(static_mpd.contains("presentationTimeOffset=\"360000\""));
        assert!(!static_mpd.contains("availabilityStartTime"));
    }

    #[test]
    fn object_authentication_detects_header_and_payload_changes() {
        let key = [11u8; 32];
        let tag = authenticate_object(&key, b"header", b"payload");

        assert!(verify_object_authentication(
            &key, b"header", b"payload", &tag
        ));
        assert!(!verify_object_authentication(
            &key, b"other", b"payload", &tag
        ));
        assert!(!verify_object_authentication(
            &key, b"header", b"other", &tag
        ));
    }
    #[test]
    fn every_byte_of_a_sample_is_covered_by_the_subsample_table() {
        // CENC requires the subsample table to account for the whole sample:
        // each entry is (clear, encrypted) and the sum must equal its length.
        // A decoder handed a table that stops short has no defined way to read
        // the rest, which is why this fails silently rather than loudly.
        let key = [7u8; 16];
        let cases: &[(&str, &[u8])] = &[
            (
                "ordinary slice",
                &[0, 0, 0, 1, 0x65, 1, 2, 3, 4, 5, 6, 7, 8],
            ),
            // A one-byte NAL: an end-of-sequence or end-of-stream marker is
            // exactly this, and a static picture is where an encoder emits the
            // smallest units it has.
            (
                "one-byte NAL present",
                &[0, 0, 0, 1, 0x65, 9, 9, 9, 0, 0, 0, 1, 0x0a],
            ),
        ];
        for (name, annex_b) in cases {
            let fragment = build_fragment(
                Some(&key),
                FragmentInput {
                    sequence: 1,
                    decode_time: 0,
                    duration: 3000,
                    keyframe: true,
                    annex_b,
                    iv: [1u8; 16],
                },
            )
            .unwrap_or_else(|error| panic!("{name}: {error}"));
            let covered: usize = fragment
                .subsamples
                .iter()
                .map(|s| usize::from(s.clear_bytes) + s.encrypted_bytes as usize)
                .sum();
            assert_eq!(
                covered,
                fragment.encrypted_sample.len(),
                "{name}: subsample table covers {covered} of {} sample bytes",
                fragment.encrypted_sample.len()
            );
        }
    }
}
